### ISSUE TITLE
Which type of data does the UART0 receive?

### ISSUE THREAD

**Issue by gkarun876** [heethesh/Autonomous-Indoor-Navigation-using-Image-Processing#2]
@heethesh  Sir, in firebird 5 code, whichtype of data does the UART0 receive? either ASCII or hex type. Because in some part of code, for checking condition, hex value is equalled and in some areas of code, ASCII value is equalled. For eg: for buzzer , (if data==hex value) and for motion (if data == ascii)?

**Comment by heethesh** [comment]
Serial bytes (8-bit commands). I don't think I've used ASCII representation anywhere, I just used the 8-bit set of commands (which are listed [here](https://github.com/heethesh/Autonomous-Indoor-Navigation-using-Image-Processing#encoded-commands-used-in-serial-communication)). The if-checks just switch between the decimal and hex representations, they're the same and shouldn't matter.

**Comment by gkarun876** [comment]
Thank you
