### ISSUE TITLE
What is the mode of zigbee?

### ISSUE THREAD

**Issue by gkarun876** [heethesh/Autonomous-Indoor-Navigation-using-Image-Processing#3]
@heethesh As Iam new to zigbee, may I know the zigbee connected to the PC and the one fixed in the firebird 5 kit to be kept in which mode either AT or API ? Thanks in advance.

**Comment by heethesh** [comment]
I would use API modes, see [example](https://github.com/heethesh/Balance-Bot/blob/master/code/Controller/controller.cpp#L57) and [docs (page 7)](https://github.com/heethesh/Balance-Bot/blob/master/report/Task%204%20-%20Joystick%20Controller%20and%20Theme%20Analysis.pdf). Even if you use AT mode, build your own packet with a header and handle errors using a checksum. Edit: they both use AT modes.

**Comment by gkarun876** [comment]
Ok sir, thank you for your suggestion
